[blurry]
domain = 'blurry-docs.netlify.app'
maximum_image_width = 1200
thumbnail_width = 285

[blurry.schema_data.author]
name = 'John Franey'
url = 'https://johnfraney.ca'

[blurry.schema_data.sourceOrganization]
name = 'Blurry'
